openapi: "3.0.3"
info:
  title: Lease API
  version: "1.0.0"
  description: REST API for lease lifecycle management within the Quicksol Real Estate platform.

servers:
  - url: "{base_url}/api/v1"
    variables:
      base_url:
        default: "http://localhost:8069"

security:
  - bearerAuth: []
    sessionAuth: []

paths:
  /leases:
    get:
      operationId: listLeases
      summary: List leases for a company
      tags: [Leases]
      parameters:
        - name: company_ids
          in: query
          required: true
          schema:
            type: string
          description: Comma-separated company IDs
        - name: property_id
          in: query
          schema:
            type: integer
        - name: tenant_id
          in: query
          schema:
            type: integer
        - name: status
          in: query
          schema:
            type: string
            enum: [draft, active, terminated, expired]
        - name: is_active
          in: query
          schema:
            type: string
            enum: ["true", "false"]
            default: "true"
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        "200":
          description: Paginated list of leases
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LeaseListResponse"
        "400":
          description: Missing company_ids
        "401":
          description: Unauthorized

    post:
      operationId: createLease
      summary: Create a new lease
      tags: [Leases]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LeaseCreateRequest"
      responses:
        "201":
          description: Lease created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LeaseResponse"
        "400":
          description: Validation error (dates, rent, overlapping lease)
        "404":
          description: Property or tenant not found
        "401":
          description: Unauthorized

  /leases/{id}:
    get:
      operationId: getLease
      summary: Get lease by ID
      tags: [Leases]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Lease details with property and tenant info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LeaseResponse"
        "404":
          description: Lease not found
        "403":
          description: Forbidden

    put:
      operationId: updateLease
      summary: Update lease
      tags: [Leases]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LeaseUpdateRequest"
      responses:
        "200":
          description: Lease updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LeaseResponse"
        "400":
          description: Validation error or lease is terminated
        "404":
          description: Lease not found

    delete:
      operationId: archiveLease
      summary: Archive (soft delete) lease
      tags: [Leases]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Lease archived
        "404":
          description: Lease not found

  /leases/{id}/renew:
    post:
      operationId: renewLease
      summary: Renew an active lease (extend in-place with audit)
      tags: [Leases]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LeaseRenewRequest"
      responses:
        "200":
          description: Lease renewed, audit history created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LeaseResponse"
        "400":
          description: Lease not active or invalid dates
        "404":
          description: Lease not found

  /leases/{id}/terminate:
    post:
      operationId: terminateLease
      summary: Terminate an active lease early
      tags: [Leases]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LeaseTerminateRequest"
      responses:
        "200":
          description: Lease terminated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LeaseResponse"
        "400":
          description: Lease not active
        "404":
          description: Lease not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    sessionAuth:
      type: apiKey
      in: header
      name: X-Openerp-Session-Id

  schemas:
    LeaseCreateRequest:
      type: object
      required: [property_id, tenant_id, company_id, start_date, end_date, rent_amount]
      properties:
        property_id:
          type: integer
        tenant_id:
          type: integer
        company_id:
          type: integer
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
        rent_amount:
          type: number
          format: float
          minimum: 0.01

    LeaseUpdateRequest:
      type: object
      properties:
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
        rent_amount:
          type: number
          format: float
          minimum: 0.01

    LeaseRenewRequest:
      type: object
      required: [new_end_date]
      properties:
        new_end_date:
          type: string
          format: date
          description: New end date (must be after current end_date)
        new_rent_amount:
          type: number
          format: float
          minimum: 0.01
          description: Optional updated rent
        reason:
          type: string
          description: Reason for renewal

    LeaseTerminateRequest:
      type: object
      required: [termination_date]
      properties:
        termination_date:
          type: string
          format: date
          description: Date of early termination
        reason:
          type: string
          description: Reason for termination
        penalty_amount:
          type: number
          format: float
          minimum: 0
          description: Optional penalty (informational only)

    LeaseResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          $ref: "#/components/schemas/Lease"
        _links:
          type: object

    LeaseListResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: array
          items:
            $ref: "#/components/schemas/Lease"
        meta:
          $ref: "#/components/schemas/PaginationMeta"
        _links:
          type: object

    Lease:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          description: Auto-computed reference
        property_id:
          type: integer
        property_name:
          type: string
        tenant_id:
          type: integer
        tenant_name:
          type: string
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
        rent_amount:
          type: number
          format: float
        status:
          type: string
          enum: [draft, active, terminated, expired]
        active:
          type: boolean
        termination_date:
          type: string
          format: date
        termination_reason:
          type: string
        termination_penalty:
          type: number
        company_ids:
          type: array
          items:
            type: integer
        renewal_count:
          type: integer

    PaginationMeta:
      type: object
      properties:
        total:
          type: integer
        page:
          type: integer
        page_size:
          type: integer
        total_pages:
          type: integer
