openapi: "3.0.3"
info:
  title: Tenant API
  version: "1.0.0"
  description: REST API for tenant management within the Quicksol Real Estate platform.

servers:
  - url: "{base_url}/api/v1"
    variables:
      base_url:
        default: "http://localhost:8069"

security:
  - bearerAuth: []
    sessionAuth: []

paths:
  /tenants:
    get:
      operationId: listTenants
      summary: List tenants for a company
      tags: [Tenants]
      parameters:
        - name: company_ids
          in: query
          required: true
          schema:
            type: string
          description: Comma-separated company IDs
        - name: search
          in: query
          schema:
            type: string
          description: Search by name, email, or phone
        - name: is_active
          in: query
          schema:
            type: string
            enum: ["true", "false"]
            default: "true"
          description: Filter by active status
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        "200":
          description: Paginated list of tenants
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TenantListResponse"
        "400":
          description: Missing company_ids
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden — company not authorized

    post:
      operationId: createTenant
      summary: Create a new tenant
      tags: [Tenants]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TenantCreateRequest"
      responses:
        "201":
          description: Tenant created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TenantResponse"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized

  /tenants/{id}:
    get:
      operationId: getTenant
      summary: Get tenant by ID
      tags: [Tenants]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Tenant details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TenantResponse"
        "404":
          description: Tenant not found
        "403":
          description: Forbidden — tenant not in user's company

    put:
      operationId: updateTenant
      summary: Update tenant
      tags: [Tenants]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TenantUpdateRequest"
      responses:
        "200":
          description: Tenant updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TenantResponse"
        "400":
          description: Validation error
        "404":
          description: Tenant not found

    delete:
      operationId: archiveTenant
      summary: Archive (soft delete) tenant
      tags: [Tenants]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Tenant archived
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "404":
          description: Tenant not found

  /tenants/{id}/leases:
    get:
      operationId: listTenantLeases
      summary: List all leases for a specific tenant
      tags: [Tenants]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: List of tenant leases
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LeaseListResponse"
        "404":
          description: Tenant not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    sessionAuth:
      type: apiKey
      in: header
      name: X-Openerp-Session-Id

  schemas:
    TenantCreateRequest:
      type: object
      required: [name, company_id]
      properties:
        name:
          type: string
          maxLength: 100
        phone:
          type: string
          maxLength: 20
        email:
          type: string
          format: email
          maxLength: 120
        occupation:
          type: string
          maxLength: 100
        birthdate:
          type: string
          format: date
        company_id:
          type: integer
          description: Primary company ID

    TenantUpdateRequest:
      type: object
      properties:
        name:
          type: string
        phone:
          type: string
        email:
          type: string
          format: email
        occupation:
          type: string
        birthdate:
          type: string
          format: date

    TenantResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          $ref: "#/components/schemas/Tenant"
        _links:
          type: object

    TenantListResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: array
          items:
            $ref: "#/components/schemas/Tenant"
        meta:
          $ref: "#/components/schemas/PaginationMeta"
        _links:
          type: object

    Tenant:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        phone:
          type: string
        email:
          type: string
        occupation:
          type: string
        birthdate:
          type: string
          format: date
        active:
          type: boolean
        company_ids:
          type: array
          items:
            type: integer
        lease_count:
          type: integer

    LeaseListResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: array
          items:
            type: object

    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          default: false
        message:
          type: string
        errors:
          type: object

    PaginationMeta:
      type: object
      properties:
        total:
          type: integer
        page:
          type: integer
        page_size:
          type: integer
        total_pages:
          type: integer
