#!/usr/bin/env bash
# Helper function to get both OAuth2 JWT token AND Odoo session cookie
# Most endpoints in Feature 007 require BOTH @require_jwt and @require_session
# 
# Usage:
#   source lib/get_auth_headers.sh
#   get_full_auth  # Sets ACCESS_TOKEN and creates cookie file
#   curl -X POST "$BASE_URL/api/v1/companies" \
#     -H "Authorization: Bearer $ACCESS_TOKEN" \
#     -b /tmp/odoo_test_session.txt \
#     -H "Content-Type: application/json"

get_full_auth() {
    # Load .env for database name
    SCRIPT_DIR_LOCAL="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    ENV_FILE="${SCRIPT_DIR_LOCAL}/../../18.0/.env"
    
    if [ -f "$ENV_FILE" ]; then
        set -a
        source "$ENV_FILE"
        set +a
    fi
    
    BASE_URL="${BASE_URL:-http://localhost:8069}"
    DB_NAME="${POSTGRES_DB:-realestate}"
    
    # Step 1: Get OAuth2 JWT token
    CLIENT_ID="${OAUTH2_CLIENT_ID:-test-client-id}"
    CLIENT_SECRET="${OAUTH2_CLIENT_SECRET:-test-client-secret-12345}"
    
    TOKEN_RESPONSE=$(curl -s -X POST "${BASE_URL}/api/v1/auth/token" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -d "grant_type=client_credentials&client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}")
    
    ACCESS_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.access_token // empty')
    
    if [ -z "$ACCESS_TOKEN" ] || [ "$ACCESS_TOKEN" = "null" ]; then
        echo "ERROR: Failed to get OAuth2 access token" >&2
        echo "Response: $TOKEN_RESPONSE" >&2
        return 1
    fi
    
    # Step 2: Get API session via /api/v1/users/login
    # This creates a thedevkitchen.api.session record (not just web session)
    ADMIN_LOGIN="${TEST_USER_ADMIN_LOGIN:-admin}"
    ADMIN_PASSWORD="${TEST_USER_ADMIN_PASSWORD:-admin}"
    
    SESSION_RESPONSE=$(curl -s -X POST "${BASE_URL}/api/v1/users/login" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${ACCESS_TOKEN}" \
        -d "{
            \"jsonrpc\": \"2.0\",
            \"method\": \"call\",
            \"params\": {
                \"email\": \"${ADMIN_LOGIN}\",
                \"password\": \"${ADMIN_PASSWORD}\"
            },
            \"id\": 1
        }")
    
    # Extract session_id and user_id from result
    SESSION_ID=$(echo "$SESSION_RESPONSE" | jq -r '.result.session_id // empty')
    ADMIN_UID=$(echo "$SESSION_RESPONSE" | jq -r '.result.user.id // empty')
    
    if [ -z "$SESSION_ID" ] || [ "$SESSION_ID" = "null" ]; then
        echo "ERROR: Failed to get API session" >&2
        echo "Response: $SESSION_RESPONSE" >&2
        return 1
    fi
    
    # Create cookie file manually with the session_id from JSON response
    # This ensures we use the API session_id, not the web session cookie
    cat > /tmp/odoo_test_session.txt << EOF
# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_localhost	FALSE	/	FALSE	$(( $(date +%s) + 3600 ))	session_id	${SESSION_ID}
EOF
    
    if [ -z "$ADMIN_UID" ] || [ "$ADMIN_UID" = "null" ] || [ "$ADMIN_UID" = "false" ]; then
        echo "ERROR: Failed to get Odoo session" >&2
        echo "Response: $SESSION_RESPONSE" >&2
        return 1
    fi
    
    # Export for use in caller script
    export ACCESS_TOKEN
    export ADMIN_UID
    export SESSION_COOKIE_FILE="/tmp/odoo_test_session.txt"
    
    return 0
}
